import React, { useState, useEffect, useRef } from 'react';
import { TravelItinerary, Activity, DayPlan, Event, UserProfile } from '../types';
import { Button } from './ui/Button';
import { getExtraRecommendations, getRealTimeExchangeRate, getDestinationEvents } from '../services/geminiService';
import { ACCOMMODATION_IMAGES } from '../constants';
import { 
  ArrowLeftIcon, 
  DownloadIcon, 
  ChevronDownIcon, 
  FileTextIcon, 
  ClipboardIcon, 
  MailIcon, 
  MapPinIcon, 
  BanknoteIcon, 
  WalletIcon, 
  PlusIcon, 
  InfoIcon, 
  LuggageIcon, 
  HotelIcon, 
  SparklesIcon, 
  ExternalLinkIcon,
  LinkIcon,
  CarIcon,
  UsersIcon,
  UserIcon
} from './ui/Icons';

interface ItineraryDisplayProps {
  data: TravelItinerary;
  onReset: () => void;
  city: string;
  interests: string[];
  travelParty?: UserProfile[]; 
  onItineraryChange?: (updated: TravelItinerary) => void;
}


export const ItineraryDisplay: React.FC<ItineraryDisplayProps> = ({ 
  data, 
  onReset, 
  city, 
  interests, 
  travelParty = [],
  onItineraryChange
}) => {
  // Ensure data has all required fields with defaults
  const safeData: TravelItinerary = {
    tripName: data.tripName || 'My Trip',
    summary: data.summary || '',
    localCurrency: data.localCurrency || '',
    localTransportation: data.localTransportation || '',
    weatherExpectation: data.weatherExpectation || '',
    localEtiquette: Array.isArray(data.localEtiquette) ? data.localEtiquette : [],
    packingList: Array.isArray(data.packingList) ? data.packingList : [],
    dailyItinerary: Array.isArray(data.dailyItinerary) ? data.dailyItinerary.map(day => ({
      ...day,
      activities: Array.isArray(day.activities) ? day.activities : []
    })) : [],
    accommodationRecommendations: Array.isArray(data.accommodationRecommendations) ? data.accommodationRecommendations : [],
    ...data
  };
  
  const [itinerary, setItinerary] = useState<TravelItinerary>(safeData);
  const [recommendations, setRecommendations] = useState<Activity[]>([]);
  const [events, setEvents] = useState<Event[]>([]);
  const [isLoadingRecs, setIsLoadingRecs] = useState(false);
  const [activeTab, setActiveTab] = useState<'places' | 'events'>('places');
  const [exchangeRate, setExchangeRate] = useState<string | null>(null);
  
  const [showAddForm, setShowAddForm] = useState<number | null>(null); 
  const [customActivity, setCustomActivity] = useState<Partial<Activity>>({
    activity: '', time: '12:00 PM', location: city, cost: '', description: ''
  });

  const [packingList, setPackingList] = useState<string[]>(Array.isArray(data.packingList) ? data.packingList : []);
  const [checkedItems, setCheckedItems] = useState<Set<number>>(new Set());
  const [newPackingItem, setNewPackingItem] = useState("");

  const [isExportOpen, setIsExportOpen] = useState(false);
  const [copyFeedback, setCopyFeedback] = useState("Copy Text");
  const exportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (exportRef.current && !exportRef.current.contains(event.target as Node)) {
        setIsExportOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const toggleExportMenu = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsExportOpen(!isExportOpen);
  };

  const handlePrint = () => {
    setIsExportOpen(false);
    window.print();
  };

  const formatItineraryText = () => {
    let text = `${itinerary.tripName}\n${itinerary.summary}\n\n`;
    text += `Dates: ${itinerary.dailyItinerary[0]?.date || 'Start'} to ${itinerary.dailyItinerary[itinerary.dailyItinerary.length-1]?.date || 'End'}\n\n`;
    
    itinerary.dailyItinerary.forEach(day => {
        text += `Day ${day.dayNumber}: ${day.theme} (${day.date || ''})\n`;
        text += `--------------------------------\n`;
        day.activities.forEach(act => {
            text += `[${act.time}] ${act.activity}\n`;
            if(act.location) text += `📍 ${act.location}\n`;
            if(act.cost) text += `💰 ${act.cost}\n`;
            text += `${act.description}\n\n`;
        });
        text += `\n`;
    });

    text += `Transport: ${itinerary.localTransportation}\n`;
    text += `Packing List:\n${packingList.map(i => `- ${i}`).join('\n')}\n`;
    text += `\nGenerated by WanderPlan AI`;
    return text;
  };

  const handleCopyText = async () => {
    const text = formatItineraryText();
    try {
        await navigator.clipboard.writeText(text);
        setCopyFeedback("Copied!");
        setTimeout(() => setCopyFeedback("Copy Text"), 2000);
    } catch (err) {
        console.error('Failed to copy', err);
        const textArea = document.createElement("textarea");
        textArea.value = text;
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        try {
          document.execCommand('copy');
          setCopyFeedback("Copied!");
          setTimeout(() => setCopyFeedback("Copy Text"), 2000);
        } catch (err) {
          console.error('Fallback copy failed', err);
        }
        document.body.removeChild(textArea);
    }
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`Travel Plan: ${itinerary.tripName}`);
    const body = encodeURIComponent(formatItineraryText());
    window.open(`mailto:?subject=${subject}&body=${body}`);
    setIsExportOpen(false);
  };

  const getMapsLink = (placeName: string, address: string) => {
    const query = encodeURIComponent(`${placeName} ${address} ${city}`);
    return `https://www.google.com/maps/search/?api=1&query=${query}`;
  };

  const getHotelLink = (hotelName: string) => {
     const query = encodeURIComponent(`${hotelName} hotel ${city} booking`);
     return `https://www.google.com/search?q=${query}`;
  };

  const getAccommodationImage = (type: string, name: string) => {
    const lowerType = type.toLowerCase();
    let category = 'hotel';
    if (lowerType.includes('resort') || lowerType.includes('villa')) category = 'resort';
    else if (lowerType.includes('hostel') || lowerType.includes('dorm')) category = 'hostel';
    else if (lowerType.includes('apartment') || lowerType.includes('airbnb') || lowerType.includes('flat')) category = 'airbnb';
    
    const images = ACCOMMODATION_IMAGES[category] || ACCOMMODATION_IMAGES.hotel;
    let hash = 0;
    for (let i = 0; i < name.length; i++) {
      hash = name.charCodeAt(i) + ((hash << 5) - hash);
    }
    const index = Math.abs(hash) % images.length;
    return images[index];
  };

  const renderStars = (rating?: number) => {
    if (!rating) return null;
    return (
      <div className="flex items-center text-stone-900 font-bold text-xs">
        <span className="mr-0.5">★</span> {rating}
      </div>
    );
  };

  useEffect(() => {
    const loadData = async () => {
       setIsLoadingRecs(true);
       try {
         const startDate = itinerary.dailyItinerary[0]?.date || "upcoming";
         const endDate = itinerary.dailyItinerary[itinerary.dailyItinerary.length - 1]?.date || "upcoming";

         const [recs, rate, fetchedEvents] = await Promise.all([
            getExtraRecommendations(city, interests),
            getRealTimeExchangeRate("USD", city),
            getDestinationEvents(city, startDate, endDate)
         ]);
         
         setRecommendations(recs);
         setEvents(fetchedEvents);
         if (rate && rate !== "Same Currency") {
            setExchangeRate(rate);
         }
       } catch (e) {
         console.error(e);
       } finally {
         setIsLoadingRecs(false);
       }
    };
    loadData();
  }, [city, interests]);

  const addActivity = (dayNumber: number, activity: Activity) => {
    const newItinerary = { ...itinerary };
    const day = newItinerary.dailyItinerary.find(d => d.dayNumber === dayNumber);
    if (day) {
      day.activities.push({
         ...activity, 
         time: activity.time === "Flex" ? "Flex Time" : activity.time,
      });
      day.activities.sort((a, b) => a.time.localeCompare(b.time));
    }
    setItinerary(newItinerary);
    if (onItineraryChange) onItineraryChange(newItinerary); 
    setShowAddForm(null);
  };

  const addPackingItem = () => {
     if (!newPackingItem.trim()) return;
     const updatedList = [...packingList, newPackingItem.trim()];
     setPackingList(updatedList);
     setNewPackingItem("");
     
     const newItinerary = { ...itinerary, packingList: updatedList };
     setItinerary(newItinerary);
     if (onItineraryChange) onItineraryChange(newItinerary);
  };

  const togglePackingItem = (idx: number) => {
    const newChecked = new Set(checkedItems);
    if (newChecked.has(idx)) {
      newChecked.delete(idx);
    } else {
      newChecked.add(idx);
    }
    setCheckedItems(newChecked);
  };

  const sources = recommendations.length > 0 && recommendations[0].sourceUrls ? recommendations[0].sourceUrls : [];

  return (
    <div className="max-w-6xl mx-auto px-4 py-12 font-sans text-stone-900">
      
      {/* Main Content */}
      <div className="min-w-0">
        <div className="flex justify-between items-center mb-10 no-print relative z-50">
            <Button variant="ghost" onClick={onReset} className="flex items-center gap-2 pl-0 hover:bg-transparent hover:text-stone-500">
              <ArrowLeftIcon className="w-5 h-5" /> Plan Another
            </Button>
            
            <div className="relative" ref={exportRef}>
                <Button 
                    onClick={toggleExportMenu} 
                    variant="outline"
                    className="flex items-center gap-2"
                >
                    <DownloadIcon className="w-4 h-4" /> Export <ChevronDownIcon className="w-3 h-3 opacity-70" />
                </Button>
                
                {isExportOpen && (
                    <div className="absolute right-0 mt-2 w-64 bg-white rounded-lg shadow-xl border border-stone-100 overflow-hidden animate-in fade-in zoom-in-95 origin-top-right">
                        <button 
                            onClick={handlePrint}
                            className="w-full text-left px-4 py-3 text-sm text-stone-700 hover:bg-stone-50 transition-colors flex items-center gap-3 border-b border-stone-50"
                        >
                            <FileTextIcon className="w-4 h-4 text-stone-400" /> Save as PDF
                        </button>
                        <button 
                            onClick={handleEmail}
                            className="w-full text-left px-4 py-3 text-sm text-stone-700 hover:bg-stone-50 transition-colors flex items-center gap-3 border-b border-stone-50"
                        >
                            <MailIcon className="w-4 h-4 text-stone-400" /> Share via Email
                        </button>
                        <button 
                            onClick={handleCopyText}
                            className="w-full text-left px-4 py-3 text-sm text-stone-700 hover:bg-stone-50 transition-colors flex items-center gap-3"
                        >
                            <ClipboardIcon className="w-4 h-4 text-stone-400" /> {copyFeedback}
                        </button>
                    </div>
                )}
            </div>
        </div>

        {/* MAIN ITINERARY CARD */}
        <div className="bg-white shadow-sm rounded-xl border border-stone-200 mb-12 overflow-hidden print-container">
            {/* Header / Banner */}
            <div className="p-8 md:p-12 border-b border-stone-100 relative">
                <div className="max-w-4xl">
                    <div className="flex flex-wrap gap-3 mb-6">
                        <span className="inline-flex items-center px-3 py-1 rounded-full border border-stone-200 bg-stone-50 text-xs font-bold uppercase tracking-wider text-stone-600">
                            🌤 {itinerary.weatherExpectation}
                        </span>
                        <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-stone-200 bg-stone-50 text-xs font-bold uppercase tracking-wider text-stone-600">
                            <BanknoteIcon className="w-3 h-3" />
                            {exchangeRate ? `${exchangeRate} • ` : ''}{itinerary.localCurrency}
                        </span>
                    </div>

                    <h1 className="text-4xl md:text-6xl font-playfair font-bold mb-6 text-stone-900 leading-tight">{itinerary.tripName}</h1>
                    <p className="text-stone-500 text-lg leading-relaxed max-w-2xl font-light">{itinerary.summary}</p>
                </div>

                 {/* Travel Party Avatars */}
                 {travelParty && travelParty.length > 0 && (
                    <div className="mt-8 flex items-center gap-4 border-t border-stone-100 pt-6">
                        <span className="text-xs font-bold uppercase tracking-widest text-stone-400">Travel Party</span>
                        <div className="flex -space-x-2">
                            {travelParty.map((u, i) => (
                                <div key={i} className="w-8 h-8 rounded-full border-2 border-white bg-stone-100 flex items-center justify-center overflow-hidden shadow-sm" title={u.name}>
                                    {u.avatar ? (
                                        <img src={u.avatar} alt={u.name} className="w-full h-full object-cover" />
                                    ) : (
                                        <span className="text-xs font-bold text-stone-900">{u.name[0]}</span>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>

            <div className="p-8 md:p-12 bg-white">
            
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                {/* Main Itinerary Column */}
                <div className="lg:col-span-8 space-y-16">
                    <div>
                        <h2 className="text-xl font-bold font-playfair text-stone-900 mb-10 pb-4 border-b border-stone-100">Daily Plan</h2>
                        
                        {itinerary.dailyItinerary.map((day) => (
                        <div key={day.dayNumber} className="relative pl-8 print-break-inside-avoid mb-12 last:mb-0">
                            {/* Minimal Timeline Line */}
                            <div className="absolute left-0 top-2 bottom-0 w-px bg-stone-200"></div>
                            
                            <div className="mb-8 relative flex items-baseline gap-4">
                                <span className="absolute left-[-4px] top-2 h-2 w-2 rounded-full bg-stone-900 ring-4 ring-white"></span>
                                <h3 className="text-xl font-bold text-stone-900 font-playfair">Day {day.dayNumber}</h3>
                                <div className="text-sm font-bold text-stone-400 uppercase tracking-wider">{day.theme}</div>
                            </div>

                            <div className="space-y-10">
                            {day.activities.map((act, idx) => (
                                <div key={idx} className="group relative">
                                    <div className="flex gap-4 items-start">
                                        <div className="w-16 flex-shrink-0 pt-1">
                                            <span className="text-xs font-mono font-bold text-stone-500 block">
                                                {act.time}
                                            </span>
                                        </div>
                                        
                                        <div className="flex-1">
                                            <div className="mb-2">
                                                <a 
                                                    href={getMapsLink(act.activity, act.location)} 
                                                    target="_blank" 
                                                    rel="noopener noreferrer"
                                                    className="text-lg font-bold text-stone-900 hover:underline decoration-stone-300 underline-offset-4 transition-all"
                                                >
                                                    {act.activity}
                                                </a>
                                            </div>
                                            
                                            <div className="flex items-center gap-3 mb-3">
                                                {act.rating && renderStars(act.rating)}
                                                {act.rating && <span className="text-stone-300 text-xs">•</span>}
                                                <div className="flex items-center gap-1 text-xs text-stone-500 font-medium bg-stone-50 px-2 py-0.5 rounded">
                                                    {act.cost}
                                                </div>
                                            </div>

                                            <p className="text-stone-600 text-sm leading-relaxed">
                                                {act.description}
                                            </p>
                                            
                                            {act.location && (
                                                <div className="mt-2">
                                                     <a href={getMapsLink(act.activity, act.location)} target="_blank" className="text-xs text-stone-400 hover:text-stone-800 flex items-center gap-1 transition-colors">
                                                        <MapPinIcon className="w-3 h-3" /> {act.location} <span className="ml-1 opacity-70">(View Map & Hours)</span>
                                                     </a>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            ))}
                            </div>
                            
                            {showAddForm !== day.dayNumber && (
                            <button 
                                onClick={() => setShowAddForm(day.dayNumber)}
                                className="w-full mt-8 py-3 border border-dashed border-stone-200 rounded-lg text-stone-400 text-sm hover:border-stone-400 hover:text-stone-700 hover:bg-stone-50 transition-all duration-200 flex items-center justify-center gap-2 group no-print"
                            >
                                <PlusIcon className="w-4 h-4" /> Add Activity
                            </button>
                            )}

                            {showAddForm === day.dayNumber && (
                            <div className="mt-8 p-6 bg-stone-50 rounded-lg border border-stone-200 animate-in fade-in no-print">
                                <h4 className="font-bold text-stone-900 mb-4 text-sm">Add Activity</h4>
                                <div className="grid grid-cols-2 gap-4 mb-4">
                                    <div className="col-span-2 md:col-span-1">
                                        <input 
                                            className="w-full border border-stone-200 rounded p-2 text-sm bg-white" 
                                            placeholder="Activity Name" 
                                            value={customActivity.activity}
                                            onChange={e => setCustomActivity({...customActivity, activity: e.target.value})}
                                        />
                                    </div>
                                    <div className="col-span-2 md:col-span-1">
                                        <input 
                                            className="w-full border border-stone-200 rounded p-2 text-sm bg-white" 
                                            placeholder="Time (e.g. 2:00 PM)" 
                                            value={customActivity.time}
                                            onChange={e => setCustomActivity({...customActivity, time: e.target.value})}
                                        />
                                    </div>
                                </div>
                                <div className="flex gap-2 justify-end">
                                    <Button variant="ghost" onClick={() => setShowAddForm(null)} className="py-1 px-3 text-xs h-8">Cancel</Button>
                                    <Button 
                                        onClick={() => addActivity(day.dayNumber, customActivity as Activity)} 
                                        disabled={!customActivity.activity}
                                        className="py-1 px-3 text-xs h-8"
                                    >
                                        Add
                                    </Button>
                                </div>
                            </div>
                            )}
                        </div>
                        ))}
                    </div>
                </div>

                {/* Sidebar Info Column */}
                <div className="lg:col-span-4 space-y-8">
                
                {/* Transport */}
                {itinerary.localTransportation && (
                   <div className="print-break-inside-avoid p-6 bg-stone-50 rounded-xl border border-stone-100">
                      <h3 className="text-sm font-bold text-stone-900 mb-3 uppercase tracking-wider flex items-center gap-2">
                        <CarIcon className="w-4 h-4" /> Getting Around
                      </h3>
                      <p className="text-sm text-stone-600 leading-relaxed font-serif italic">
                        "{itinerary.localTransportation}"
                      </p>
                   </div>
                )}

                {/* Etiquette */}
                <div className="print-break-inside-avoid p-6 border border-stone-200 rounded-xl">
                    <h3 className="text-sm font-bold text-stone-900 mb-4 uppercase tracking-wider flex items-center gap-2">
                        <InfoIcon className="w-4 h-4" /> Good to Know
                    </h3>
                    <ul className="space-y-3">
                    {itinerary.localEtiquette.map((tip, idx) => (
                        <li key={idx} className="text-sm text-stone-600 flex gap-2">
                            <span className="text-stone-300">•</span> {tip}
                        </li>
                    ))}
                    </ul>
                </div>

                {/* Packing List */}
                <div className="print-break-inside-avoid">
                    <h3 className="text-sm font-bold text-stone-900 mb-4 uppercase tracking-wider flex items-center gap-2">
                      <LuggageIcon className="w-4 h-4" /> Packing Essentials
                    </h3>
                    <ul className="space-y-2 mb-4">
                      {packingList.map((item, idx) => {
                          const isChecked = checkedItems.has(idx);
                          return (
                          <li 
                            key={idx} 
                            onClick={() => togglePackingItem(idx)}
                            className={`flex items-center text-sm px-3 py-2 rounded border shadow-sm cursor-pointer transition-all select-none ${
                                isChecked 
                                ? 'bg-stone-50 text-stone-400 border-stone-100' 
                                : 'bg-white text-stone-700 border-stone-200 hover:border-stone-300'
                            }`}
                          >
                             <div className={`w-4 h-4 rounded-full border mr-3 flex-shrink-0 flex items-center justify-center transition-colors ${
                                 isChecked ? 'bg-stone-200 border-stone-200' : 'border-stone-300 bg-white'
                             }`}>
                                 {isChecked && <svg className="w-2.5 h-2.5 text-stone-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>}
                             </div>
                             <span className={isChecked ? 'line-through' : ''}>{item}</span>
                          </li>
                      )})}
                    </ul>
                    <div className="flex gap-2 no-print">
                        <input 
                           type="text" 
                           className="flex-1 border border-stone-200 rounded px-3 py-2 text-sm bg-white outline-none focus:border-stone-400"
                           placeholder="Add item..."
                           value={newPackingItem}
                           onChange={(e) => setNewPackingItem(e.target.value)}
                           onKeyDown={(e) => e.key === 'Enter' && addPackingItem()}
                        />
                        <button 
                           onClick={addPackingItem}
                           disabled={!newPackingItem.trim()}
                           className="bg-stone-100 hover:bg-stone-200 text-stone-600 p-2 rounded transition-colors border border-stone-200"
                        >
                           <PlusIcon className="w-4 h-4" />
                        </button>
                    </div>
                </div>
                </div>
            </div>

            </div>
        </div>

        {/* Accommodation Section */}
        {itinerary.accommodationRecommendations && itinerary.accommodationRecommendations.length > 0 && (
            <div className="no-print mb-16">
                <h3 className="text-2xl font-playfair font-bold text-stone-900 mb-6 flex items-center gap-3">
                    <HotelIcon className="w-5 h-5 text-stone-500" /> Where to Stay
                </h3>
                
                <div className="flex overflow-x-auto pb-8 gap-6 snap-x snap-mandatory scrollbar-hide">
                    {itinerary.accommodationRecommendations.map((acc, idx) => (
                    <div key={idx} className="min-w-[300px] md:min-w-[340px] bg-white border border-stone-200 rounded-xl hover:border-stone-400 transition-all flex flex-col h-full group overflow-hidden snap-center shadow-sm">
                        
                        <div className="h-48 overflow-hidden relative grayscale group-hover:grayscale-0 transition-all duration-500">
                            <img 
                                src={getAccommodationImage(acc.type, acc.name)} 
                                alt={acc.type}
                                className="w-full h-full object-cover"
                            />
                            <div className="absolute top-4 left-4">
                                <span className="bg-white/90 backdrop-blur-sm text-stone-900 text-[10px] font-bold px-2 py-1 rounded uppercase tracking-wider border border-stone-200">
                                    {acc.type}
                                </span>
                            </div>
                        </div>

                        <div className="p-6 flex flex-col flex-grow">
                            <div className="flex justify-between items-start mb-2">
                                <a 
                                    href={getHotelLink(acc.name)}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="block group-hover:underline decoration-stone-300 underline-offset-4"
                                >
                                    <h4 className="text-lg font-bold text-stone-900 font-playfair">{acc.name}</h4>
                                </a>
                            </div>
                            <div className="mb-4">{renderStars(acc.rating)}</div>
                            
                            <p className="text-sm text-stone-500 leading-relaxed mb-6 flex-grow line-clamp-3">
                                {acc.reason}
                            </p>
                            
                            <div className="flex justify-between items-center pt-4 border-t border-stone-100 mt-auto">
                                <span className="font-bold text-sm text-stone-900">{acc.estimatedCost}</span>
                                <a 
                                    href={getHotelLink(acc.name)}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-xs font-bold uppercase tracking-wider text-stone-400 hover:text-stone-900 flex items-center gap-1 transition-colors"
                                >
                                    Check Rates <ExternalLinkIcon className="w-3 h-3" />
                                </a>
                            </div>
                        </div>
                    </div>
                    ))}
                </div>
            </div>
        )}

        {/* Live Web Results Section */}
        <div className="no-print pb-20">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4 border-b border-stone-200 pb-4">
               <div>
                  <h3 className="text-2xl font-playfair font-bold text-stone-900 flex items-center gap-2">
                     <SparklesIcon className="w-5 h-5 text-stone-400" /> Curated Extras
                  </h3>
                  <p className="text-sm text-stone-500 mt-1">Real-time findings to supplement your plan.</p>
               </div>
               
               {/* Minimal Tabs */}
               <div className="flex gap-6">
                 <button 
                   onClick={() => setActiveTab('places')}
                   className={`text-sm font-bold uppercase tracking-widest py-2 transition-all border-b-2 ${activeTab === 'places' ? 'border-stone-900 text-stone-900' : 'border-transparent text-stone-400 hover:text-stone-600'}`}
                 >
                   Trending Extras
                 </button>
                 <button 
                   onClick={() => setActiveTab('events')}
                   className={`text-sm font-bold uppercase tracking-widest py-2 transition-all border-b-2 ${activeTab === 'events' ? 'border-stone-900 text-stone-900' : 'border-transparent text-stone-400 hover:text-stone-600'}`}
                 >
                   Upcoming Events
                 </button>
               </div>
            </div>

            {isLoadingRecs ? (
                <>
                    {/* Places Skeleton */}
                    {activeTab === 'places' && (
                        <div className="flex items-stretch overflow-x-auto pb-4 gap-6 snap-x snap-mandatory scrollbar-hide">
                            {[1, 2, 3].map(i => (
                                <div key={i} className="min-w-[300px] md:min-w-[320px] bg-white p-6 rounded-xl border border-stone-200 shadow-sm snap-center flex flex-col h-full">
                                    <div className="flex justify-between items-start mb-3">
                                        <div className="h-6 bg-stone-200 rounded w-3/4 animate-pulse"></div>
                                        <div className="h-4 bg-stone-200 rounded w-12 animate-pulse"></div>
                                    </div>
                                    <div className="space-y-2 mb-6 flex-grow">
                                        <div className="h-4 bg-stone-200 rounded w-full animate-pulse"></div>
                                        <div className="h-4 bg-stone-200 rounded w-5/6 animate-pulse"></div>
                                        <div className="h-4 bg-stone-200 rounded w-4/6 animate-pulse"></div>
                                    </div>
                                    <div className="flex justify-between items-center mt-auto pt-4 border-t border-stone-100">
                                        <div className="h-4 bg-stone-200 rounded w-20 animate-pulse"></div>
                                        <div className="flex gap-1">
                                            <div className="h-6 bg-stone-200 rounded w-8 animate-pulse"></div>
                                            <div className="h-6 bg-stone-200 rounded w-8 animate-pulse"></div>
                                            <div className="h-6 bg-stone-200 rounded w-8 animate-pulse"></div>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                    
                    {/* Events Skeleton */}
                    {activeTab === 'events' && (
                        <div className="flex items-stretch overflow-x-auto pb-4 gap-6 snap-x snap-mandatory scrollbar-hide">
                            {[1, 2, 3].map(i => (
                                <div key={i} className="min-w-[300px] md:min-w-[320px] bg-white p-6 rounded-xl border border-stone-200 shadow-sm snap-center flex flex-col h-full">
                                    <div className="h-5 bg-stone-200 rounded w-24 mb-3 animate-pulse"></div>
                                    <div className="h-6 bg-stone-200 rounded w-full mb-2 animate-pulse"></div>
                                    <div className="h-3 bg-stone-200 rounded w-2/3 mb-4 animate-pulse"></div>
                                    <div className="space-y-2 flex-grow">
                                        <div className="h-4 bg-stone-200 rounded w-full animate-pulse"></div>
                                        <div className="h-4 bg-stone-200 rounded w-5/6 animate-pulse"></div>
                                        <div className="h-4 bg-stone-200 rounded w-4/6 animate-pulse"></div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </>
            ) : (
              <>
                {/* PLACES TAB */}
                {activeTab === 'places' && (
                  <div className="flex items-stretch overflow-x-auto pb-4 gap-6 snap-x snap-mandatory scrollbar-hide animate-in fade-in">
                      {recommendations.length > 0 ? recommendations.map((rec, idx) => (
                          <div key={idx} className="min-w-[300px] md:min-w-[320px] bg-white p-6 rounded-xl border border-stone-200 hover:border-stone-400 transition-all snap-center flex flex-col h-full shadow-sm">
                              <div className="flex justify-between items-start mb-3">
                                  <h4 className="font-bold text-stone-900 font-playfair text-lg">{rec.activity}</h4>
                                  {renderStars(rec.rating)}
                              </div>
                              <p className="text-sm text-stone-500 mb-6 line-clamp-3 flex-grow leading-relaxed">{rec.description}</p>
                              <div className="flex justify-between items-center mt-auto pt-4 border-t border-stone-100">
                                  <span className="text-xs font-mono text-stone-400">{rec.cost}</span>
                                  <div className="flex gap-1">
                                      {[1, 2, 3].slice(0, itinerary.dailyItinerary.length).map(d => (
                                          <button 
                                            key={d}
                                            onClick={() => addActivity(d, rec)}
                                            className="text-[10px] bg-stone-100 hover:bg-stone-200 text-stone-600 px-2 py-1 rounded font-bold transition-colors border border-stone-200"
                                            title={`Add to Day ${d}`}
                                          >
                                              + D{d}
                                          </button>
                                      ))}
                                  </div>
                              </div>
                          </div>
                      )) : (
                        <div className="col-span-full text-stone-400 text-sm font-mono">No places found.</div>
                      )}
                  </div>
                )}

                {/* EVENTS TAB */}
                {activeTab === 'events' && (
                  <div className="flex items-stretch overflow-x-auto pb-4 gap-6 snap-x snap-mandatory scrollbar-hide animate-in fade-in">
                      {events.length > 0 ? events.map((event, idx) => (
                        <div key={idx} className="min-w-[300px] md:min-w-[320px] bg-white p-6 rounded-xl border border-stone-200 hover:border-stone-400 transition-all snap-center flex flex-col h-full shadow-sm">
                            <div className="text-[10px] font-bold text-stone-500 uppercase tracking-widest mb-3 border border-stone-200 inline-block px-2 py-1 rounded self-start">{event.date}</div>
                            <h4 className="font-bold text-stone-900 font-playfair text-lg mb-2">
                              {event.link ? (
                                <a href={event.link} target="_blank" rel="noopener noreferrer" className="hover:underline decoration-stone-300 underline-offset-4 flex items-center gap-1">
                                    {event.name} <ExternalLinkIcon className="w-3 h-3" />
                                </a>
                              ) : event.name}
                            </h4>
                            <p className="text-xs text-stone-400 mb-4 flex items-center font-mono">
                                <MapPinIcon className="w-3 h-3 mr-1" /> {event.location}
                            </p>
                            <p className="text-sm text-stone-500 line-clamp-3 flex-grow leading-relaxed">{event.description}</p>
                        </div>
                      )) : (
                         <div className="col-span-full text-stone-400 text-sm font-mono">
                           No specific events found.
                         </div>
                      )}
                  </div>
                )}
              </>
            )}
                    
            {/* Sources */}
            {sources.length > 0 && activeTab === 'places' && (
                <div className="mt-8 pt-6 border-t border-stone-200">
                    <p className="text-[10px] font-bold text-stone-400 uppercase tracking-widest mb-3">Verified Sources</p>
                    <ul className="flex flex-wrap gap-4">
                      {sources.slice(0, 5).map((url, i) => (
                          <li key={i}>
                            <a href={url} target="_blank" rel="noopener noreferrer" className="text-xs text-stone-500 hover:text-stone-900 hover:underline flex items-center gap-1">
                                <LinkIcon className="w-3 h-3" /> {new URL(url).hostname.replace('www.', '')}
                            </a>
                          </li>
                      ))}
                    </ul>
                </div>
            )}
        </div>

      </div>
    </div>
  );
};